# Generated by Django 4.1.7 on 2023-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='no_picture.png', upload_to='products')),
                ('synopsis', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
